name = "SamApp2025"
uuid = "0771bc02-3f64-4ea7-890c-a2e30890e189"
authors = ["Jorge FdCD <jorge.fdcd@icloud.com>"]
version = "15.2.2-DEV"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
BioAlignments = "00701ae9-d1dc-5365-b64a-a3a3ebf5695e"
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DCAUtils = "e41cd558-3099-4f6e-a65d-5336857e40aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"
Gzip_jll = "be1be57a-8558-53c3-a7e5-50095f79957e"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Infernal = "4aa08641-d763-4623-9c5b-cef742500064"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Logomaker = "3e22dfff-eee4-477b-ac6a-6f7f49e5ccf0"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NaNStatistics = "b946abbf-3ea7-4610-9019-9858bfdeaf2d"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RestrictedBoltzmannMachines = "12e6b396-7db5-4506-8cb6-664a4fe1e50e"
Rfam = "38c5b72b-a3f0-437e-9f79-f3da4655de63"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StringDistances = "88034a9c-02f8-509d-84a9-84ec65e18404"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
ViennaRNA = "05a721ad-238d-4945-8c85-8b5c1fff3465"
ViennaRNA_jll = "b7a990de-7fa3-5a2e-8a39-d875e4dafecd"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
Artifacts = "1.10"
BioAlignments = "3.1.0"
BioSequences = "3"
CSV = "0.10"
CairoMakie = "0.11,0.12,0.13"
CodecZlib = "0.7"
DCAUtils = "1"
DataFrames = "1"
Dates = "1"
DelimitedFiles = "1"
Distributions = "0.25"
Downloads = "1"
EllipsisNotation = "1"
FASTX = "2"
Gzip_jll = "1"
HDF5 = "0.17"
Infernal = "1"
JLD2 = "0.4,0.5"
KernelDensity = "0.6"
LazyArtifacts = "1.10"
LinearAlgebra = "1"
LogExpFunctions = "0.3"
Logging = "1"
LoggingExtras = "1"
Logomaker = "1.0.1, 2"
Makie = "0.20,0.21,0.22"
NaNStatistics = "0.6"
Preferences = "1"
PythonPlot = "1.0.6"
Random = "1"
RestrictedBoltzmannMachines = "1, 2, 3"
Rfam = "3.1.0"
Statistics = "1.10"
StatsBase = "0.34.3"
StringDistances = "0.11"
Unitful = "1.19.1"
ViennaRNA = "0.11.1"
ViennaRNA_jll = "2.6.4"
XLSX = "0.8, 0.9, 0.10"
julia = "1.10"
